version: "3.5"

networks:
  ai-docks-net:
    driver: bridge

services:
  # webapp:
  #   build:
  #     context: ./webapp
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     - AUTH_SECRET=${APP_AUTH_SECRET}
  #     - NEXTAUTH_URL=${DOMAIN}
  #   env_file:
  #     - .env
  #   tty: true # enable colorized logs
  #   volumes:
  #     - ./webapp/:/usr/src/app/
  #     - hf-cache:/.hf-cache
  #   logging:
  #     options:
  #       max-size: "100m"
  #       max-file: "10"
  #   restart: always
  #   networks:
  #     - ai-docks-net
  #   ports:
  #     - 3333:3000
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://webapp:80/"]
  #     interval: 1m
  #     timeout: 20m
  #     retries: 20

  ai-docks-service:
    volumes:
      - ./api:/app/:rw
      - ./api/models/emb:/app/models/emb:rw
      - ./api/models/rr:/app/models/rr:rw
      - ./api/models/llm:/app/models/llm:rw
      - ../primsa-ai/training/app/models/:/fine-tunes
      - hf-cache:/.hf-cache
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    ipc: host
    tty: true # enable colorized logs
    env_file:
      - .env
    container_name: ai-docks
    build:
      context: .
    ports:
      - 8723:80
    networks:
      - ai-docks-net
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_HOME=/.hf-cache
    logging:
      options:
        max-size: "100m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ai-docks:80/"]
      interval: 1m
      timeout: 20m
      retries: 20

volumes:
  hf-cache:
    driver: local
